server:
    verbosity: 0
    use-syslog: no
    logfile: ""
    log-servfail: yes

    interface: 127.0.0.1
    port: 5335
    access-control: 127.0.0.0/8 allow
    do-ip6: no

    username: ""
    directory: "/var/lib/unbound"
    pidfile: ""
    auto-trust-anchor-file: "/var/lib/unbound/root.key"

    prefetch: yes

    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10
